### ISSUE TITLE
vhosts using underscore break zone

### ISSUE THREAD

**Issue by jaromil** [dyne/gitzone#4]
I've noticed to my surprise that a vhost name containing an underscore breaks the zone to the point bind9 will simply not serve any of it. I'm not sure this is documented (didn't check) and this is also not covered from the zone validation scripts.

We should find out more about the issue and perhaps add an extra check made by gitzone, reporting the error and breaking the validation of the zone push.

**Comment by tg-x** [comment]
can you post an example zone file + the error messages?

**Comment by jaromil** [comment]
Somehow did not occur on a new setup, perhaps something weird in my old setup.
