### ISSUE TITLE
gitzone no longer works with current git, ref updates forbidden inside quarantine environment

### ISSUE THREAD

**Issue by zelch** [dyne/gitzone#5]
So, earlier this year git added some additional checks to prevent accidental corruption of a repository due to ref changes in a pre-receive hook.

https://www.spinics.net/lists/git/msg300763.html

The logic appears to be that since all those references go away if for some reason the receive fails, anything that you do that refers to that references would be left in a corrupt state.

This means that the commits in the pre-receive hook end up pointing to nowhere, and git gets unhappy.

gitzone looks _mostly_ safe against this, but largely because it either won't decline during a receive after making many changes, or because it works in a temporary 'new' branch that it throws away with ease.

Well, mostly, the initial check out can end up pointing to a non-existent ref.

Which leaves us in an awkward spot, because none of it will work at all with a current version of git.  The git "checkout -qf $new" on line 301 fails, and so gitzone fails.

We could probably get around a lot of the problem by doing all of the checks twice, once in pre-receive (and then junking them), and then again in post-receive.  With any commits happening in post-receive.

Except...  We can't check out the new ref to run any of the checks.

Any thoughts or suggestions?

**Comment by jaromil** [comment]
Following up our conversation on IRC, thanks for reporting this, I'll be testing your fix!

**Comment by zelch** [comment]
Have you had a chance to review and test these changes? :)

**Comment by parazyd** [comment]
Thanks! Your PR was merged.
